seed: 42

data:
  dataset: "phoenix2014"
  dataset_root: "/nas/Dataset/Phoenix/phoenix2014-release/phoenix-2014-multisigner"
  frame_subdir: "features/fullFrame-256x256px"
  preprocess_root: "./preprocess"
  gloss_dict_path: "./preprocess/phoenix2014/gloss_dict.npy"

  datatype: "video"
  frame_interval: 1
  image_scale: 1.0
  input_size: 224

  # Fallback; we will replace with model.kernel_spec after model init
  kernel_spec: ["K5","P2","K5","P2"]

  batch_size: 4
  num_workers: 4

model:
  name: "legacy_slowfast"
  num_classes: 1296
  blank_id: 0

  # Adapter-specific args:
  c2d_type: "slowfast101"                   # authors’ R101 backbone
  slowfast_config: "SLOWFAST_64x2_R101_50_50.yaml"
  slowfast_args: []                         # you can pass cfg overrides here if needed
  conv_type: "conv1d"
  use_bn: false
  hidden_size: 1024
  load_pkl: true
  weight_norm: true
  share_classifier: true

  # used if inner.conv1d.kernel_size is unavailable
  kernel_spec: ["K5","P2","K5","P2"]

  # authors’ loss selections/weights
  loss_weights:
    SeqCTC: 1.0
    # ConvCTC: 0.0
    # Dist: 0.0

optimiser:
  name: "adamw"
  lr: 1.0e-4
  weight_decay: 1.0e-2

scheduler:
  name: "cosine"
  t_max: 50
  eta_min: 1.0e-6

trainer:
  epochs: 1
  save_dir: "outputs"
  grad_accum_steps: 1
  amp: true
  ema: false
  ema_decay: 0.999
